default_language_version:
    python: python3.9
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-docstring-first
        -   id: requirements-txt-fixer
        -   id: check-ast
        -   id: check-merge-conflict
        -   id: no-commit-to-branch
            args: ['--branch', 'master']
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v2.3.0
        hooks:
        -   id: reorder-python-imports
    -   repo: https://github.com/ambv/black
        rev: 21.9b0
        hooks:
        -   id: black
